### ISSUE TITLE
how to run against a list of target 

### ISSUE THREAD

**Issue by prosecurity** [iinc0gnit0/RBust#1]
i was wondering how you can run this agaisnt a target file eg subdomains.txt

**Comment by ghost** [comment]
I also want to see that. And an -o (output) file.txt function would be nice.

**Comment by yangr0** [comment]
Thank you both for the suggestions, skript0r and I will try our bests to add those features in there as soon as possible. But for now, we are working on some bug fixes and error handling. Again, thank you both for your feedback! We really appreciate it!
